# Generated by Django 4.0.2 on 2022-04-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerLogin', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='aliceBlueID',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
