# Generated by Django 4.1.3 on 2022-12-12 21:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registerLogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('userName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('twoFA', models.CharField(max_length=4)),
                ('password', models.CharField(max_length=50)),
                ('api_key', models.CharField(max_length=100)),
                ('api_secret', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Credential',
            },
        ),
        migrations.CreateModel(
            name='FiveMIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('timestamp', models.CharField(max_length=100)),
                ('volume', models.IntegerField(default=0)),
                ('open', models.FloatField(default=0)),
                ('close', models.FloatField(default=0)),
                ('high', models.FloatField(default=0)),
                ('low', models.FloatField(default=0)),
                ('atp', models.FloatField(default=0)),
                ('exchange', models.CharField(max_length=20)),
                ('historical_volume', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '5 MIN Candle Data',
            },
        ),
        migrations.CreateModel(
            name='OneMIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('timestamp', models.CharField(max_length=100)),
                ('volume', models.IntegerField(default=0)),
                ('open', models.FloatField(default=0)),
                ('close', models.FloatField(default=0)),
                ('high', models.FloatField(default=0)),
                ('low', models.FloatField(default=0)),
                ('atp', models.FloatField(default=0)),
                ('exchange', models.CharField(max_length=20)),
                ('historical_volume', models.IntegerField(default=0)),
                ('historical_high', models.FloatField(default=0)),
                ('historical_low', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': '1 MIN Candle Data',
            },
        ),
        migrations.CreateModel(
            name='Papertrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('signal', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50, verbose_name='Stock Name')),
                ('quantity', models.IntegerField()),
                ('buy_price', models.FloatField()),
                ('sell_price', models.FloatField()),
                ('stop_loss', models.FloatField(default=0.0)),
                ('target', models.FloatField(default=100000)),
                ('isCompleted', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=False)),
                ('start_time', models.CharField(default='00:00', max_length=100, verbose_name='Trade Started at')),
                ('end_time', models.CharField(default='00:00', max_length=100, verbose_name='Trade Ended at')),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('historical_volume', models.IntegerField(default=0, verbose_name='Historical Volume')),
                ('current_volume', models.IntegerField(default=0, verbose_name='Current Volume')),
                ('ltp', models.FloatField(default=0.0, verbose_name='LTP')),
                ('net_pl', models.FloatField(default=0.0, verbose_name='Net P/L')),
                ('net_charges', models.FloatField(default=0.0, verbose_name='Total Charges')),
                ('sl_trail', models.BooleanField(default=False)),
                ('Invested', models.FloatField(default=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Strategies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('filePath', models.FilePathField(path='/Users/nitishgupta/Desktop/algotradersonline/backend/src/strategiesAPI/scripts', unique=True)),
                ('isProduction', models.BooleanField(default=False, verbose_name='Production')),
            ],
            options={
                'verbose_name': 'Strategie',
            },
        ),
        migrations.CreateModel(
            name='TradedStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('stock_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Traded Stock',
            },
        ),
    ]
