# Generated by Django 4.1.3 on 2022-12-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategiesAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategies',
            name='filePath',
            field=models.FilePathField(path='/Users/nitishgupta/Documents/GitHub/algotradersonline/backend/src/strategiesAPI/scripts', unique=True),
        ),
    ]
