# Generated by Django 4.1.3 on 2022-12-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ltp', models.FloatField(default=0.0)),
                ('chn_prev_day', models.FloatField(default=0.0)),
                ('per_chn', models.FloatField(default=0.0)),
                ('oi_per_chn', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='NIFTY',
            fields=[
                ('Volume_C', models.FloatField(default=0.0)),
                ('OI_Change_C', models.FloatField(default=0.0)),
                ('OI_C', models.FloatField(default=0.0)),
                ('LTP_C', models.FloatField(default=0.0)),
                ('Strike_Price', models.FloatField(primary_key=True, serialize=False, verbose_name='Strike Price')),
                ('LTP_P', models.FloatField(default=0.0)),
                ('OI_P', models.FloatField(default=0.0)),
                ('OI_Change_P', models.FloatField(default=0.0)),
                ('Volume_P', models.FloatField(default=0.0)),
                ('PUT_CALL_OI_CHN', models.FloatField(default=0.0, verbose_name='PUT-CALL OI CHN')),
                ('PUT_CALL_OI', models.FloatField(default=0.0, verbose_name='PUT-CALL OI')),
                ('PCR', models.FloatField(default=0.0, verbose_name='PCR (Bullish)')),
                ('CPR', models.FloatField(default=0.0, verbose_name='CPR (Bearish)')),
                ('STRONGNESS_OF_SUPPORT', models.FloatField(default=0.0)),
                ('Reverse_Weightage', models.FloatField(default=0.0)),
                ('Buy_Sell', models.CharField(default='-', max_length=100, verbose_name='Buy/Sell')),
                ('Stongness_Level', models.CharField(default='-', max_length=100)),
                ('Immediate_Support', models.FloatField(default=0.0)),
                ('Strong_Support', models.FloatField(default=0.0)),
                ('PCR_Weightage', models.FloatField(default=0.0)),
                ('CPR_Weightage', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='NIFTY_histo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('Volume_C', models.FloatField(default=0.0)),
                ('OI_Change_C', models.FloatField(default=0.0)),
                ('OI_C', models.FloatField(default=0.0)),
                ('LTP_C', models.FloatField(default=0.0)),
                ('Strike_Price', models.FloatField(verbose_name='Strike Price')),
                ('LTP_P', models.FloatField(default=0.0)),
                ('OI_P', models.FloatField(default=0.0)),
                ('OI_Change_P', models.FloatField(default=0.0)),
                ('Volume_P', models.FloatField(default=0.0)),
                ('PUT_CALL_OI_CHN', models.FloatField(default=0.0, verbose_name='PUT-CALL OI CHN')),
                ('PUT_CALL_OI', models.FloatField(default=0.0, verbose_name='PUT-CALL OI')),
                ('PCR', models.FloatField(default=0.0, verbose_name='PCR (Bullish)')),
                ('CPR', models.FloatField(default=0.0, verbose_name='CPR (Bearish)')),
                ('STRONGNESS_OF_SUPPORT', models.FloatField(default=0.0)),
                ('Reverse_Weightage', models.FloatField(default=0.0)),
                ('Buy_Sell', models.CharField(default='-', max_length=100, verbose_name='Buy/Sell')),
                ('Stongness_Level', models.CharField(default='-', max_length=100)),
                ('Immediate_Support', models.FloatField(default=0.0)),
                ('Strong_Support', models.FloatField(default=0.0)),
                ('PCR_Weightage', models.FloatField(default=0.0)),
                ('CPR_Weightage', models.FloatField(default=0.0)),
            ],
        ),
    ]
